optimizer: 
  lr: 0.001
  base_lr: 1
  weight_decay: 0.0001
  lr_gamma: 0.001
  lr_decay: 0.75
noisy_loss: 
  alpha: 0.4
  beta: 0.1
  lambda1: 600
transfer_loss:
  eta1: 0.01
  eta2: 1.0
  epsilon: 0.01
  tau: 0.5
  