Data:
  mean: [0.03663960,0.05686222,0.07027539,0.13209523,0.15537022,0.11317099,
0.04456289,0.06727448,0.08087467,0.15668542,0.18970865,0.13845459,
0.05666387,0.08986699,0.10474999,0.23819432,0.24408186,0.17658596,
0.07191240,0.11009849,0.12804862,0.27353846,0.29506361,0.23107152,
0.02740826,0.05259311,0.04957874,0.25411300,0.16029898,0.09156227,
]
  std: [0.01806824,0.02652057,0.03369143,0.06142854,0.06327354,0.04849509,
0.02174213,0.03110296,0.03927036,0.06781353,0.07718894,0.06155256,
0.02214198,0.02898491,0.04181109,0.06902913,0.06962218,0.06281188,
0.03101570,0.04037877,0.05908670,0.07487106,0.10165328,0.10036106,
0.01900747,0.03029360,0.03520214,0.13488243,0.08013274,0.05656784,
]
  doy: [5,85,117,133,261]
Model:
  epoch: 50
  num_classes: 8
  num_seq: 5
  num_feature: 6
  batch_size: 1024
  steps_per_epoch: 500
Class_name: ["Corn","Soybean","Winter Wheat","Grassland","Other vegetable","Water","Fallow land","Impervious"]

Color_map_dict: {
0: [255,211,0],
1: [38,112,0],
2: [165,112,0],
3: [217,217,217],
4: [217,217,217],
5: [217,217,217],
6: [217,217,217],
7: [217,217,217],
255: [217,217,217],
}

File:
  train_img: ""
  train_label: ""
  val_img: ""
  val_label: ""
  test_img: ""
  test_label: ""

  train_npy_data: "/data2/ll22/Upcrop/CDL_OH_L8/pixel_sample/2020/data_npy/train_data_all.npy"
  train_npy_label: "/data2/ll22/Upcrop/CDL_OH_L8/pixel_sample/2020/label_npy/train_label_all.npy"
  train_npy_data_source: "/data2/ll22/Upcrop/CDL_OH_L8/pixel_sample/2019/data_npy/train_data_all.npy"
  train_npy_label_source: "/data2/ll22/Upcrop/CDL_OH_L8/pixel_sample/2019/label_npy/train_label_all.npy"
  train_npy_data_target: "/data2/ll22/Upcrop/CDL_OH_L8/pixel_sample/2019/data_npy/train_data_all.npy"
  train_npy_label_target: "/data2/ll22/Upcrop/CDL_OH_L8/pixel_sample/2019/label_npy/train_label_all.npy"
  val_npy_data: ""
  val_npy_label: ""
  test_npy_data: "/data2/ll22/Upcrop/CDL_OH_L8/pixel_sample/2020/data_npy/test_data_all.npy"
  test_npy_label: "/data2/ll22/Upcrop/CDL_OH_L8/pixel_sample/2020/label_npy/test_label_all.npy"
  test_npy_data_target: "/data2/ll22/Upcrop/CDL_OH_L8/pixel_sample/2019/data_npy/test_data_all.npy"
  test_npy_labelterget: "/data2/ll22/Upcrop/CDL_OH_L8/pixel_sample/2019/label_npy/test_label_all.npy"

  file_name: "cta_2019_2020"
  model_start_path: ""
  summary_path: "/data2/ll22/Upcrop/CDL_OH_L8/result/2020_cta/log/"
  model_save_path: "/data2/ll22/Upcrop/CDL_OH_L8/result/2020_cta/model/"
  train_excel_path: "/data2/ll22/Upcrop/CDL_OH_L8/result/2020_cta/train/"
  val_excel_path: "/data2/ll22/Upcrop/CDL_OH_L8/result/2020_cta/val/"
  test_excel_path: "/data2/ll22/Upcrop/CDL_OH_L8/result/2020_cta/test/"

  image_path: "/data2/ll22/Upcrop/CDL_OH_L8/Takeout/Cloud/P20R32_L8_2020"
  best_model_path: "/data2/ll22/Upcrop/CDL_OH_L8/result/2019_cta/model/time_1/epoch_50.pth"
  save_pred_file: "/data2/ll22/Upcrop/CDL_OH_L8/result/2020_transformer/pred/class/"
  save_score_file: "/data2/ll22/Upcrop/CDL_OH_L8/result/2020_transformer/pred/score/"

Mosaic:
  img_dir: "/data2/ll22/Upcrop/CDL_OH_L8/Takeout/Cloud/P20R32_CDL_2020_simply/patch" #"/data2/ll22/Upcrop/CDL_OH_L8/result/2020_transformer/pred/class/"
  save_file: "/data2/ll22/Upcrop/CDL_OH_L8/Takeout/Cloud/P20R32_CDL_2020_simply/merge/P20R32_CDL_2020.tif"#"/data2/ll22/Upcrop/CDL_OH_L8/result/2020_transformer/pred/merge/P20R32_Transformer_2020.tif"
  map_file: "/data2/ll22/Upcrop/CDL_OH_L8/Takeout/Cloud/P20R32_CDL_2020_simply/merge/P20R32_CDL_2020.tif"#"/data2/ll22/Upcrop/CDL_OH_L8/result/2020_transformer/pred/merge/P20R32_Transformer_2020_color.tif"

Understanding:
  mean: "/home/ll20/data/2021hubei_SAR_2/2021_elite_filter/result/refined_lee/PBCN_v3/understand/attenweight_mean_v2.xlsx"
  std: "/home/ll20/data/2021hubei_SAR_2/2021_elite_filter/result/refined_lee/PBCN_v3/understand/attenweight_std_v2.xlsx"